services:
  - type: web
    name: tune-teller-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PORT
        value: 5000
