services:
  - type: web
    name: tune-teller-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
    envVars:
      - key: PORT
        value: 10000
